In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr)
print("First element :",arr[0])


import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Last element :",arr[-1])


import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Third element :",arr[2])


import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Last five elements :",arr[15:])


import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Elements from index 3 to 8 :",arr[3:8])


import numpy as np
arr2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]])
print(arr2)
print("First Row :",arr2[0])


import numpy as np
arr2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]])
print(arr2)
print("Last Row :",arr2[3])


import numpy as np
arr2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]])
print("First Column :",arr2[ : ,0])


import numpy as np
arr2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]])
print("Last Column :",arr2[ : ,3])


import numpy as np
arr2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]])
print("Middle two rows :\n",arr2[1:3])


import numpy as np
arr2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]])
print("Middle two columns :\n", arr2[:, 1:3])


import numpy as np
arr2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]])
print("First 2 X 2 sub-matrix :\n",arr2[0:2])


import numpy as np
arr2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]])
print("Last 2 X 2 sub-matrix :\n",arr2[2: ])


import numpy as np
import numpy as np
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)
print("First matrix :\n",arr3[0])


import numpy as np
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)
print("Second matrix :\n",arr3[1])


import numpy as np
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)
print("Specific element :",arr3[0,1,1])


import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
even_numbers=arr[arr%2==0]
print("Even Numbers:")
print(even_numbers)


import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
odd_numbers=arr[arr%2!=0]
print("Odd numbers:")
print(odd_numbers)


import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
greater_numbers=arr[arr<10]
print("Numbers greater than 10:")
print(greater_numbers)


import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
less_numbers=arr[arr<15]
print("Numbers less than 15:")
print(less_numbers)


import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Index postions (0,2,4,6):",arr[[0,2,4,6]])


import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("First and last element :",arr[[0,19]])


import numpy as np
arr2=np.array([
    [5,10,15,20,25],
    [30,35,40,45,50],
    [55,60,65,70,75],
    [80,85,90,95,100],
    [105,110,115,120,125]
])
print("Firsst Row :",arr2[0])
print("Last Row :",arr2[4])
print("First Column :",arr2[ : ,0])
print("Last column :",arr2[ : ,4])


import numpy as np
arr=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print("First 3 columns :",arr[ : , :3])


import numpy as np
arr3=np.array([
 
   [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print("First Row :",arr3[0])
print("Last Row :",arr3[4])
print("First Column :",arr3[ : ,0])
print("Last Column :",arr3[ : ,4])
print("Middle Row :",arr3[2])
print("Middle Column :",arr3[ : ,2])
print("Top-left 2 X 2 matrix :",arr3[0:2,0:2])
print("Bottom-right 2 X 2 matrix :",arr3[3: ,3: ])
even_numbers=arr3[arr3%2==0]
print("Even numbers :")
print(even_numbers)
odd_numbers=arr3[arr3%2!=0]
print("Odd numbers :")
print(odd_numbers)
greater_numbers=arr3[arr3>15]
print("Numbers greater than 15 :")
print(greater_numbers)
less_numbers=arr3[arr3<10]
print("Numbers less than 10 :")
print(less_numbers)
print("Index positions (1,7,13,19,24) :",arr3[[0,1,2,3,4],[0,1,2,3,4]])
print(arr3[-1])
print(arr3[-2])
print(arr3[-3])
print("Last three rows :",arr3[2: ])
print("First three columns :",arr3[ : , : 3])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First element : 1
Last element : 20
Third element : 3
Last five elements : [16 17 18 19 20]
Elements from index 3 to 8 : [4 5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First Row : [1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Last Row : [13 14 15 16]
First Column : [ 1  5  9 13]
Last Column : [ 4  8 12 16]
Middle two rows :
 [[ 5  6  7  8]
 [ 9 10 11 12]]
Middle two columns :
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
First 2 X 2 sub-matrix :
 [[1 2 3 4]
 [5 6 7 8]]
Last 2 X 2 sub-matrix :
 [[ 9 10 11 12]
 [13 14 15 16]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
First matrix :
 [[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Second matrix :
 [[5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Specific element : 4
Even Numbers:
[ 2  4  6  8 10 12 14 16 18 20]
Odd numbers:
[ 1  3  5  7  9 11 13 15 17 19]
Numbers greater than 10:
[1 2 3 4 5 6 7 8 9]
Numbers less than 15:
[ 1  2  3  4  5