In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("1D Array :",arr)


import numpy as np
arr2=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]]
              )
print("2D Array :",arr2)


import numpy as np
arr3=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print("3D Array :",arr3)


import numpy as np
arr2=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]]
              )
print("Number of dimenisons of 2D Array :",arr2.ndim)


import numpy as np
arr3=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print("Shape of 3D array :",arr3.shape)


import numpy as np
arr3=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print("Total number of elements :",arr3.size)


import numpy as np
arr3=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print("Datatype of elements :",arr3.dtype)


import numpy as np
zero=np.zeros((5,5))
print(zero)


import numpy as np
one=np.ones((4,4))
print(one)


import numpy as np
marks=np.full((3,3),100)
print(marks)


import numpy as np
identity=np.full((5,5),5)
print(identity)


import numpy as np
a1=np.arange(10,50)
print(a1)


import numpy as np
a2=np.arange(5,50,5)
print(a2)


import numpy as np
l1=np.linspace(1,100,10)
print(l1)


import numpy as np
l2=np.linspace(1,10,3)
print(l2)


import numpy as np
student_marks=np.array([78,88,74,73,89,68,66,73,74,65])
print(student_marks)


import numpy as np
student_marks=np.array([78,88,74,73,89,68,66,73,74,65])
print("Shape :",student_marks.shape)
print("Number of dimensions :",student_marks.ndim)
print("Data type :",student_marks.dtype)


import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)


import numpy as np
array=np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]])
print(array)


import numpy as np
float_arr=np.array([1.0,1.5,2.0,2.5,3.0,3.5])
print(float_arr)


import numpy as np
str_arr=np.array(["Mango","Apple","Orange","Kiwi"])
print(str_arr)


import numpy as np
bool_arr=np.array([True,False,True,True,False])
print(bool_arr)


import numpy as np
zero=np.zeros((6,6))
print(zero)


import numpy as np
one=np.full((10,10),10)
print(one)




1D Array : [ 1  2  3  4  5  6  7  8  9 10]
2D Array : [[10 20 30]
 [40 50 60]
 [70 80 90]]
3D Array : [[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
Number of dimenisons of 2D Array : 2
Shape of 3D array : (2, 2, 3)
Total number of elements : 12
Datatype of elements : int64
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 5 10 15 20 25 30 35 40 45]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[ 1.   5.5 10. ]
[78 88 74 73 89 68 66 73 74 65]
Shape : (10,)
Number of dimensions : 1
Data type : int64
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[1.  1.5 2.  2.5 3.  3.5]
['Mango' 